#spring.application.name=ECom
#spring.datasource.url = jdbc:h2:mem:testdb
#spring.datasource.driverClassName = org.h2.Driver
#spring.datasource.username = sa
#spring.datasource.password = 
#
##JPA Settings
#spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#
##H2 Console Settings
#spring.h2.console.enabled = true
#
#
#spring.h2.console.path=/h2-console
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
spring.application.name=ECommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_proj
spring.datasource.username=ecom
spring.datasource.password=ecom

# JPA Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate=DEBUG
