server.port = 8081
spring.h2.console.enabled = true
# localhost:808/
# localhost:808/user
# localhost:808/admin
# localhost:808/logout
# localhost:808/h2-console  --- Database URL
#SELECT * FROM USERS;
#SELECT * FROM AUTHORITIES;